package com.server.founder.model;

public enum ResponseState {
    DENIED,INCORRECT_TOKEN_SIGN,TOKEN_EXPIRED,INCORRECT_TOKEN_TYPE,ACCESS,ALREADY_EXIST,EXIST,NOT_EXIST,INCORRECT_PASSWORD,CODE_SEND,EXCEPTION,INCORRECT_CODE,TO_MUCH,
    SUCCESS,EMPTY,FILE_ERROR,TOKEN_EXCEPTION,TOKEN_ERROR,TYPE_ERROR,YOURSELF,LENGTH_ERROR,TEXT_ERROR,NO_ACTIVE,NOT_CONTAIN,

}
